### ISSUE TITLE
updateComponent error with new monkey-patching code

### ISSUE THREAD

**Issue by thibauts** [Izzimach/react-three#12]
I get an error on [line 859](https://github.com/Izzimach/react-three/blob/master/src/ReactTHREE.js#L859)  of ReactTHREE.js with the latest git code. Everything worked fine with the npm version without monkey-patching.

`Uncaught TypeError: Cannot read property 'updateComponent' of undefined`

The setup is a simple Scene with a PerspectiveCamera, a PointLight and an Object3D containing a Mesh. The error doesn't happen on first render but does on every subsequent setState.

I'm a little bit short on time right now but will provide test code that reproduces the error if needed.

**Comment by Izzimach** [comment]
Thanks, I don't there is a test case for this yet. I think I can modify the current composite test to check this case as well. This probably effects [react-pixi](https://github.com/Izzimach/react-pixi) as well

**Comment by Izzimach** [comment]
@thibauts can you check if this fixed your bug?

**Comment by thibauts** [comment]
Just checked. The error doesn't show up anymore but now `render` isn't called when component state changes

**Comment by Izzimach** [comment]
Hm, do you have an example you can post?

**Comment by thibauts** [comment]
I had the problem at work and can't reproduce it at home with sample code. I'll check again on monday and let you know or close the issue. Thanks for your help !

**Comment by thibauts** [comment]
I still can't reproduce the bug. It probably was an error on my part. Thanks !

**Comment by Izzimach** [comment]
No problem, if you find the error go ahead and re-open. Thanks for reporting this.

**Comment by captDaylight** [comment]
I'm getting this error by requiring the reactthree:

`Warning: patching react to work with react-three`

**Comment by Izzimach** [comment]
This is fine, it's mostly there to remind me that there is some monkey-patching going on under the hood that will have to be re-written for each revision.
