### ISSUE TITLE
Issue with creating a Line with LinePieces type

### ISSUE THREAD

**Issue by robrkerr** [Izzimach/react-three#17]
According to the Three.js docs (http://threejs.org/docs/api/objects/Line.html) the attribute 'type' accepts the values THREE.LineStrip or THREE.LinePieces, but it is actually the attribute 'mode' which stores these (at least in the current version). However, react-three sets the 'type' attribute and so it is not currently possible to use THREE.LinePieces via react-three.

**Comment by Izzimach** [comment]
Looks like `type` hasn't been used for a while there. So instead of passing through `type` I should pass through `mode` instead, right?

**Comment by Izzimach** [comment]
@robrkerr  do you have any code snippet I could use as an example and/or test for this?

**Comment by robrkerr** [comment]
@Izzimach, perfect. Thanks heaps!
