### ISSUE TITLE
Physijs Support

### ISSUE THREAD

**Issue by agilgur5** [Izzimach/react-three#22]
This might be better as a separate fork called 'react-physijs', but I'd love to be able to use this with Physijs. Physijs's materials, meshes, and scenes aren't incredibly different, but I'm not sure how gravity/constraints/etc will play along with the crazy things you've done to get this to work.

**Comment by Izzimach** [comment]
Yeah, probably a separate fork. I'm not sure how this work since physijs would be modifying the object position/rotation itnernally instead of having it passed in as props. Would you just like to specify the initial object locations via React props?

**Comment by agilgur5** [comment]
Yes, that would seem the best option. Physijs would then mutate the state of the React component... though I don't believe Physijs does this immutably, which could require some workarounds.
