### ISSUE TITLE
'this._processChildContext is not a function' with react 0.13.1?

### ISSUE THREAD

**Issue by geoflo** [Izzimach/react-three#23]
I needed to change the react library dependency from 0.13.1 to 0.14.0-alpha to get the examples to work. Don't know if was just a problem with my set-up or not.

I followed these build instructions and put the whole tree in my Apache docs directory.

git clone https://github.com/Izzimach/react-three.git
cd react-three
npm install -g gulp
npm install
gulp

**Comment by Izzimach** [comment]
Thanks for the heads up!

Looks like some internal thing changed from 0.13.1 to 0.13.3. I should probably make the dependencies more version-restrictive since I'm relying on specific React internals.
