### ISSUE TITLE
Update to React 0.14

### ISSUE THREAD

**Issue by Izzimach** [Izzimach/react-three#24]
In addition to just updating the code to work with 0.14, some changes to consider:

1. Add [babel](https://babeljs.io/) to the pipeline. Not only is React using it, but ES6 is right around the corner anyways.
2. Remove DOM references if possible. Instead of creating a WebGL canvas, the user would create their own `<canvas>` element and place the `Scene` under it. This removes most dependence on the DOM although getting mouse events will have to be handled/abstracted away. Removing all DOM reference makes it easier to do item 3, which is:
3. Add some hooks to render to a native OpenGL surface instead of WebGL. This would mean adding a native lib to replace three.js functionality. It should also be compatible with [react-pixi](https://github.com/Izzimach/react-pixi)

**Comment by agrande** [comment]
Any progress on this?
Is there a way I can help?

**Comment by fsbdev** [comment]
What about implementing a Canvas component in ReactTHREE/ReactPIXI that uses DOM canvas in default implementation but users can create and pass in their own implementations for other platforms?

**Comment by fsbdev** [comment]
You'll have to create an abstraction over react-three, react-pixi, and whatever the react-opengl suggestion uses (needs a specific example of an OpenGL scene graph/rendering library).

**Comment by Izzimach** [comment]
For native OpenGL version a completely new version of threejs would be needed which maintains and renders the scene graph in native data structures. This should probably wait until React 0.14. The initial version will probably run on desktop first (via Qt or FLTK) since I haven't worked much on iOS or Android.

**Comment by Izzimach** [comment]
The initial upgrade to use 0.14 is at b8f8ce1faee5eca52066e345f58a63827f924a9c which works with React `0.14.0-rc1` with minimal changes. Hopefully this means an easy transition when 0.14 comes out for real.

**Comment by Izzimach** [comment]
Version `0.7.0` using `React 0.14` is up and published. Tested it with r3test but there may be broken bits.
