### ISSUE TITLE
Passing the up vector to cameras

### ISSUE THREAD

**Issue by evilfer** [Izzimach/react-three#25]
Hi I'm using react-three with a custom camera movement implementation. I run into problems when the camera would not keep its up vector as desired, and I didn't found any way of passing my own calculated up vector to it.

So I've made a small change to the code, if interested see https://github.com/evilfer/react-three/blob/master/src/ReactTHREE.js#L189

Do you think this is a suitable way of solving this issue? Is it worth creating a pull request?

**Comment by Izzimach** [comment]
Oops, I've not tried to use a custom up vector before. Yeah, create a PR for this and I'll merge. If you can also link to an example gist that would help me create and test and/or example for it.
