### ISSUE TITLE
Any plans on supporting PostProcessing Effects?

### ISSUE THREAD

**Issue by mattrei** [Izzimach/react-three#31]
So far react-three is just great. Having a the scenegraph built out with React components feels so natural. Anyway I am currently testing and I think it is not possible to add PostProcessing effects to the scene. At least the API is not up yet and I do not want to mingle-mangle around before having your opinion on it.

What are your plans for this issue? 

Best

**Comment by Izzimach** [comment]
I guess you are talking about `THREE.EffectComposer`? I haven't any plans but it looks like something that should definitely be added as a prop or wrapper to the scene.

However, if instead you want direct manipulation using full-screen quads and/or renderTarget access you are probably better off writing a custom component for it.

**Comment by masonicboom** [comment]
@mattrei I have a fork over at https://github.com/masonicboom/react-three/tree/effects that lets you specify an effect as a prop on the scene (this commit: https://github.com/masonicboom/react-three/commit/e31fac94b52b888821321efa74318f021722adf7).

I built it in a rush to get https://github.com/masonicboom/react-cardboard working, so I'm not sure the API is right (e.g. do people want to specify multiple effects?). If you want it though, @Izzimach, I'm happy to make a PR.

**Comment by Izzimach** [comment]
Yeah sure, make sure it passes the tests and PR it, I'll throw it in there!

**Comment by Izzimach** [comment]
Closing since this seems similar to #74
