### ISSUE TITLE
Performance issues when animating lots of objects

### ISSUE THREAD

**Issue by mattrei** [Izzimach/react-three#33]
Hi,

I am currently learning Threejs with React. So please bare with me eventually :).

I have around 200 small cubes on the screen which are all moving towards the camer/usera, if they are behind the camera they cubes will be positioned at the horizont again (and then they make up their way towards the camera/user again and again).

Following your example code, each ```<Cube>``` stores its Z-position in its state and on every requestAnimationFrame that position is modified and therefore rerendered.
This works like a charm however my system goes down after lets say 20 seconds. The more cubes I have the sooner Chrome comes completely unusable.

I think it has to do with the requestAnimationFrame that each cube is using. I think this is very ineffecient, compared to other non React ThreeJS examples that have only *one* requestAnimationFrame.

What can you suggest for the implementation? I think this is the best approach in the React philosophy to handle the position in the <Cube> class and not in any parent container. 
So am I right with the conclusion that react-three is not suitable for animating lots of objects in a scene?

I have the following components:
Cubes: builds up the array of Cube's and sets the inital position
Cube: stores its Z-position as state, animation is done here

Thanks for your help,
Matthias

**Comment by Izzimach** [comment]
That is correct, if you are updating every cube every frame then React will probably not work will for you. You can try to batch up the changes but I don't think that will help much.

In the future we may have ways to make this work better. However, right now if you have many things moving around at once you will still get more performance by working directly with threejs.
