### ISSUE TITLE
new three.ImageUtils.loadTexture , gives error "document is not defined";

### ISSUE THREAD

**Issue by tonis2** [Izzimach/react-three#35]
`material = new three.MeshPhongMaterial({map: new three.ImageUtils.loadTexture('earthmap.jpg')})`
When i try to import material then i always get error document is not defined, what could be wrong ?

**Comment by Izzimach** [comment]
I'm not sure what could be wrong with that. Where did you put the picture? Can you post a gist of the code?

**Comment by tonis2** [comment]
Im guessing its a problem with `webpack`, is there anyway i get require image with webpack and then send this `var` to `loadTexture`?
Here the link 
https://github.com/tonis2/redux-blog/blob/master/src/views/three.js

**Comment by Izzimach** [comment]
Well, `loadTexture` should accept any URL as the texture source, even one generated by webpack. Did you try something like `new three.ImageUtils.loadTexture(require('earthmap.jpg'))` and have `url-loader` handle it like you mentioned?

**Comment by tonis2** [comment]
Got it fixed, it only worked when i added loadTexture into `componentDidMount()`;
like 
  `componentDidMount() {`
   ` let earthmap = three.ImageUtils.loadTexture('earthmap.jpg');`
    `this.setState({earth:earthmap});`
`}`
and `material = new three.MeshBasicMaterial( { map:this.state.earth, color: 0xff0000 } ),`

I am not sure why but it works.
