### ISSUE TITLE
Quaterion rotation animating causes serious lag and eventually crashes window. 

### ISSUE THREAD

**Issue by tonis2** [Izzimach/react-three#36]
Help needed, i am trying to create regular quaterion animation with `requestAnimationFrame()`, but it always causes some serious  performance troubles and also causes crash after like 60 seconds, and also get an error `Invalid array buffer length`.
It works fine if i use `setInterval()` with over 500ms delay, to create animation.
Here is how i added the animation.
```  constructor(props){
    super(props);
    this.state = {
      earth:'',
      bumps:'',
      position:new three.Vector3(-40,0,0),
      rotation:2
    }
    this._animate = this._animate.bind(this);
  }
  _animate() {
     requestAnimationFrame(this._animate);
    this.setState({rotation:this.state.rotation + 0.2});

 }

  componentDidMount() {
    let earthmap = three.ImageUtils.loadTexture('earthmap.jpg');
    let bumps = three.ImageUtils.loadTexture('bumps.jpg');
    this.setState({earth:earthmap,bumps:bumps});
    this._animate();
  }
  render () {
    const {rotation,position,earth,bumps} = this.state;



      let modelQuaternion = new three.Quaternion().setFromEuler(new three.Euler(0,0,rotation));
  <Object3D quaternion={modelQuaternion}>
            <Mesh  {...meshprops}/>
          </Object3D>

**Comment by Izzimach** [comment]
Hm, I don't see anything obviously wrong. Maybe I will write up an ES6 version of the cupcake example later this week to see if that works correctly.

**Comment by tonis2** [comment]
I think that its not case about react-three, some why `setting state` while `requestingAnimationFrame`, makes things slow, very weird.

**Comment by tonis2** [comment]
Got a little bit smarter, to make it work.  I had to add three.js to html file , 
using `import THREE from 'three';` seems to break some things.
