### ISSUE TITLE
commonjs config incorrect?

### ISSUE THREAD

**Issue by gilbox** [Izzimach/react-three#46]
It's possible I just don't understand how commonjs works, but it looks like the configuration in `dev` branch is not correct. The output file `react-three-commonjs.js` contains libs other than `react-three`. 

I have about a dozen public npm packages and none of them are distributed with sub-dependencies like this so it doesn't really make sense to me to do it this way.

**Comment by Izzimach** [comment]
I haven't actually published the stuff in `dev` so it's likely broken, yeah. But the [webpack config for commonjs](https://github.com/Izzimach/react-three/blob/dev/webpack-commonjs.config.js) specifies `React` and `THREE` as externals so they shouldn't get included. Or are you referring to some other dependency? I probably threw lodash in there without thinking about it.

**Comment by gilbox** [comment]
honestly i don't know anymore. possibly i was just tired and confused. will check it out again and let you know if I see any issues.

**Comment by gilbox** [comment]
sorry about this. i was totally wrong. all is well.
