### ISSUE TITLE
Limit orbit controls to the rendered canvas

### ISSUE THREAD

**Issue by jonaskello** [Izzimach/react-three#50]
I have a scenario where we have a 3D scene embedded into a larger react app. The problem I am seeing is that orbit controls will take input from the whole document rather than just the 3D scene canvas. Eg. text inputs that are placed at the side of the 3D scene does only respond to orbit controls.

The function for OrbitControls looks like it takes a DOM element that will limtit what it takes input from:

	THREE.OrbitControls = function ( object, domElement ) {

		this.object = object;
		this.domElement = ( domElement !== undefined ) ? domElement : document;
		// other code ...
	}

However in react-three the canvas is not passed in as domElement, so it defaults to the whole document as per the code above. Currently THREEScene.js looks like this:

    componentDidMount() {
        var renderelement = ReactDOM.findDOMNode(this);
		// other code ....
		this.mountOrbitControls(props);
	}
If we could change it to something like this maybe the orbit controls would be limited to the scene canvas:

    componentDidMount() {
        var renderelement = ReactDOM.findDOMNode(this);
		// other code ....
		this.mountOrbitControls(props, renderelement);
	}

    mountOrbitControls(props, renderelement) {
        if (props.orbitControls) {
            if (!this.orbitControls) {
                this.orbitControls = new props.orbitControls(this._THREEcamera, renderelement);
            }
        }
    }

Or is there some other way to limit the orbit controls to only take input from the 3D scene and not the surrounding parts of the document?

**Comment by arnaudmolo** [comment]
I am having the exact same problem, so +1 :)

**Comment by jonaskello** [comment]
@arnaudmolo Nice, that looks like the simplest thing that would solve it. Hoping we can get this merged.

**Comment by jonaskello** [comment]
Thanks for merging this! I built and tested it with our app locally and it works perfectly! Looking forward to seeing this fix reach npmjs :-)
