### ISSUE TITLE
componentWillReceiveProps vs receiveComponent ?

### ISSUE THREAD

**Issue by gilbox** [Izzimach/react-three#53]
@Izzimach, I was wondering why you used the internal method `receiveComponent` in `THREEObject3dMixin.js`. Would `componentWillReceiveProps` work just as well?

**Comment by Izzimach** [comment]
`componentWillReceiveProps` is used with components defined by `React.createClass`. For React internal components there is a whole different set of methods such as `mountComponent` and `receiveComponent` among others. If you look you'll see that THREEScene is the only component defined using `createClass`

**Comment by gilbox** [comment]
explains a lot. thanks!
