### ISSUE TITLE
Why lock to react 0.14.0 ?

### ISSUE THREAD

**Issue by gilbox** [Izzimach/react-three#56]
Hi, I was just wondering why you don't use `^0.14.0` in `package.json` ?

I tested with `react@0.14.1` one time and it seemed to work fine.

**Comment by Izzimach** [comment]
As mentioned in https://github.com/Izzimach/react-three/issues/23 there are sometimes issues with using different React versions, even if it's just a patch-level change. If all the tests pass I can just update the `package.json` and publish. Looks like they just moved to 0.14.2 though!

**Comment by gilbox** [comment]
makes sense, thanks
