### ISSUE TITLE
Raycaster and OrthographicCamera camera miss clicks

### ISSUE THREAD

**Issue by TimurAditazz** [Izzimach/react-three#73]
camera-up.js example doesn't work properly if perspective camera changet to othographic, it has wrong mouse click coordinates. 0.7.5

    return React.createElement(ReactTHREE.OrthographicCamera,
      {
        name:'maincamera',
        fov:75,
        aspect:this.props.aspectratio,
        position: cameraposition,
        lookat: new THREE.Vector3(0,0,0),
        up: cameraup,
        near:1,
        far:5000,
        left: window.innerWidth/-2,
        right: window.innerWidth/2,
        top: window.innerHeight/2,
        bottom: window.innerHeight/-2

      });

looks like it remove cube only if the cube on line from camera to center

**Comment by TimurAditazz** [comment]
Fx can be
for 2edd453129e0e72d680a5cb5d75fedde99c2dcc0:

replace
276       mousecoords.unproject(camera);
277       raycaster.ray.set( camera.position, mousecoords.sub( camera.position ).normalize() );
to
             raycaster.setFromCamera( mousecoords, camera );

If this fix is good, would you make version 0.7.6

**Comment by Izzimach** [comment]
Thanks for catching that!

Published as 0.8.0 which also includes a new Renderer/Scene setup, so watch out for that.

**Comment by TimurAditazz** [comment]
Thank you for this great tool!

**Comment by Izzimach** [comment]
Thanks for catching that!

Published as 0.8.0 which also includes a new Renderer/Scene setup, so watch out for that.
