### ISSUE TITLE
readme says pointerEvents is property for the Renderer, but pointerEvents are for Scene

### ISSUE THREAD

**Issue by macrozone** [Izzimach/react-three#88]
Some confusion in the readme here: https://github.com/Izzimach/react-three/blob/1d446545cbeb44993e515dc45fd02e4d0193986d/README.md#extra-props

pointerEvents should be defined on the `<Scene />` not on the `<Renderer />`. Example "interactive" uses it correctly.

should i do a PR?

**Comment by Izzimach** [comment]
Oops, at some point the `<Renderer>` and `<Scene>` components got a major rework and this was probably missed. If you want to make a PR to update the docs that would be great.
