### ISSUE TITLE
Using react-three with Typescript

### ISSUE THREAD

**Issue by jugglingcats** [Izzimach/react-three#89]
Wondered if there are any Typescript bindings for this project planned, or if anyone has it working within a Typescript project. Thanks

**Comment by huyqut** [comment]
Hi, I also come across this problem as well. Don't we have any plans in the future for this?

**Comment by Izzimach** [comment]
I don't use Typescript, so I can't really add refs. Someone added .d.ts files to [react-pixi](https://github.com/Izzimach/react-pixi), could someone knowledgeable in Typescript do the same for react-three?
