### ISSUE TITLE
react-three with react 15.4

### ISSUE THREAD

**Issue by eeh** [Izzimach/react-three#90]
Hi,

The React guys released 15.4 a few days ago, and it got picked up by my build server today. Unfortunately, react-three seems to be incompatible with this version of react. 

It appears that the react guys have done some reorganizing, removing ReactDOM from the react/lib and a couple of things like that. 

Reverting to React 15.3 in the meantime.

Regards,
Emil

**Comment by Izzimach** [comment]
Yeah, similar to #82 and #48 no doubt. Thanks for the heads up!

Should maybe switch back to React version locking or using a custom React lib.

**Comment by eeh** [comment]
Thanks!

Will you publish a new version on npm?

**Comment by Izzimach** [comment]
Published!
