### ISSUE TITLE
Spherical Panorama Example gives error

### ISSUE THREAD

**Issue by Dhyey** [Izzimach/react-three#95]
Hi when I ran `npm run example` and then opened this example I get error as

<img width="726" alt="screen shot 2017-01-04 at 7 17 49 pm" src="https://cloud.githubusercontent.com/assets/6316380/21644237/90fcad2a-d2b2-11e6-929a-8e23417d82e7.png">

**Comment by Izzimach** [comment]
Yeah, at some point we switched to a Renderer/Scene architecture (to support multiple scenes on one canvas) and this was never updated.

**Comment by Dhyey** [comment]
Thank you!
